name: testing actions
on: push

jobs:
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello actions!"
      - name: multiline string
        run: |
          php -v
          composer -v
      - name: phyton Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-windows-commands:
    runs-on: windows-latest
    needs: [runs-shell-command]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash